;WRITE A PROGRAM TO COPY 10 NUMBERS STORED FROM 30H MEMORY LOCATION.
;THE NUMBERS SHOULD BE COPIED TO MEMORY LOCATION STARTING FROM 40H MEMORY LOCATION
	
        ORG 0000H

        MOV R3,#0AH
        MOV R0,#30H
        MOV R1,#40H
		
AGAIN:	MOV A,@R0
		XCH A,@R1
		MOV @R0,A
		INC R1
		INC R0
		DJNZ R3, AGAIN
		
		END